### ISSUE TITLE
app uses googleapis.com

### ISSUE THREAD

**Issue by ponrun** [urbit/create-landscape-app#11]
i would feel much more warm and fuzzy if the app didn't talk to google every time i opened it.

https://github.com/urbit/create-landscape-app/blob/master/full/src/css/fonts.css

lines 1-26 load the font from media.urbit.org. would it be possible to do the same with the rest?

**Comment by matildepark** [comment]
It looks like these two URI both resolve successfully:

```
https://storage.googleapis.com/media.urbit.org/fonts/scp-extralight.woff
https://media.urbit.org/fonts/scp-extralight.woff
```

So it's equivalent for your need. As to changing that in the code, I would be wary of deviating from its boilerplates in the [main codebase](https://github.com/urbit/urbit), which have the same URI for those fonts. If it changes in future, I'll try to mirror it.

Personally, given this is OS-level stuff, I feel like we should be hosting the fonts locally on ships, not relying on the broader internet for our interface — but given our current application structure is pretty monolithic, this would lead to duplicate font storage, which is not ideal. I'll make note of this for further discussion and see how we can approach that.

**Comment by matildepark** [comment]
We don't use these fonts anymore.
