### ISSUE TITLE
Tile Image is missing from generator

### ISSUE THREAD

**Issue by benjaminkwilliams** [urbit/create-landscape-app#21]
I tried to copy from chat's tile.js file to add an image to my tile.js, it didn't work our so well.
`b.createElement("img",{className:"absolute invert-d",style:{left:39,top:39},src:"/~chat/img/Tile.png",width:48,height:48,__self:this,__source:{fileName:j,lineNumber:46}}`

I changed b to react and the path to my path, but it still didn't work.
Can we get the correct code added to the generator with a dummy "~" image so things look pretty.

**Comment by matildepark** [comment]
I'm confused by this. Were you editing the compiled JS inside your ship? You should be making changes in the create-landscape-app repository, which has the source code, and using `npm run serve`.

**Comment by matildepark** [comment]
Also note that it's unclear if you `|commit %home`d when you finished that edit; we also have an issue where you'll need to `:goad %force` and force refresh in your browser after the commit.

**Comment by benjaminkwilliams** [comment]
Yes I was editing the generated tile.js file in my app, yes I did run `|commit %home` and used CTRL+F5 in Chrome to reload Landscape. All my edits did work, but there is no img src tag in ./tile/tile.js
`  render() {
    return (
      <div className="w-100 h-100 relative bg-white bg-gray0-d ba b--black b--gray1-d">
        <a className="w-100 h-100 db pa2 no-underline" href="/~histar">
          <p className="black white-d absolute f9" style={{ left: 8, top: 8 }}>histar</p>
        </a>
      </div>
    );`

If I wanted to add an image, where does it go?

**Comment by matildepark** [comment]
You can just add <img src=“/~histar/image.png” /> and include the image.png in your ship’s /app/histar/img folder.

— 
~haddef-sigwen
https://urbit.org

**Comment by benjaminkwilliams** [comment]
Cool thanks!

~linrun-harmes

**Comment by benjaminkwilliams** [comment]
So this is the final product that got a "centered" image within the tile
`react.createElement('img', { className:"absolute invert-d", style: {left:39,top:39}, src: "/~histar/img/Tile.png", width:48, height:48,  __self: this, __source: {fileName: _jsxFileName, lineNumber: 12}} )`

I add to add the `className:"absolute invert-d", style: {left:39,top:39},` and `width:48, height:48,` to tile.js after running `npm run build` but prior to `|commit %home`. If that can be automated then it should be good to go.

**Comment by matildepark** [comment]
I still don’t understand why you’re editing the compiled JS?

— 
~haddef-sigwen
https://urbit.org

**Comment by benjaminkwilliams** [comment]
Because the image wasn’t centered in the tile post compile, using the raw html provided `<img src="/~histar/image.png" />` in the precompilied file did not generate a centered image post compile.

**Comment by matildepark** [comment]
Try adding style={{top: 48, left: 48}} to the img tag in the source code.

**Comment by benjaminkwilliams** [comment]
That produces `react.createElement('img', { src: "/~histar/img/Tile.png", style: {top: 48, left: 48}, __self: this, __source: {fileName: _jsxFileName, lineNumber: 12}})` in the output, therefore I just need to add the className tag to the img tag. Again, having it already present in the source (even commented out) would make things easier.

**Comment by matildepark** [comment]
Right right it’s className=“absolute”

I mean if you want, feel free to PR. However I don’t think this is the kind of elusive, idiosyncratic Landscape code that needs example; it’s just adding an img element in React.
