### ISSUE TITLE
Which arm passes the ship name?

### ISSUE THREAD

**Issue by cxk280** [urbit/create-landscape-app#23]
According to the `README`, the ship name is supposed to be passed to the frontend in an arm called `peer-[yourappname]tile`, but this does not appear anywhere in the code and so I presume that line of the `README` is out of date. My best guess is it's referring to the `poke-handle-http-request` arm in `<yourappname>.hoon`, but I'm not quite sure. What is the general path that ship-stored data passes in the Hoon files before it is sent to the frontend?

**Comment by matildepark** [comment]
Yes, that's pre-static gall changes ... at the time, the `peer-[yourappname]tile` was a Gall arm that handled peer requests using the `[yourappname]tile` wire. We still can handle those, we just use `on-watch`. Here's a [great example](https://github.com/urbit/urbit/blob/master/pkg/arvo/app/clock.hoon#L93). If the path the subscription is initiated upon in front-end (by using `api.bind`) is `clocktile`, we pass state to the front-end as JSON.

**Comment by matildepark** [comment]
Basically, in our [tile example](https://github.com/urbit/create-landscape-app/blob/master/urbit/app/smol.hoon#L51), you'd want `our` instead of that `~` I believe.

**Comment by cxk280** [comment]
In the tile example, do you mean the line `[[%give %fact ~ %json !>(*json)]~ this]` should be `[[%give %fact our %json !>(*json)]~ this]`?

**Comment by matildepark** [comment]
It actually might be replacing the *json instead of the ~, sorry.

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
What is this doing differently, exactly? Everything seems to load the same as before.

**Comment by matildepark** [comment]
*json is a bunted JSON, a blank JSON. Usually you want to pass state; “our" is our ship name. So, upon opening a subscription to the tile, on that path, we respond with “our”, converted to JSON.

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
Let's back up a second before I get confused. The ship's name is already being successfully sent to the frontend. It gets added to the `window` object as `window.ship` and is displayed in `src/js/components/lib/header-bar.js`. This all happens immediately when using the boilerplate with no changes whatsoever. So it is clear that the general pipeline of getting information in, or at least about, the ship to the UI is already there. I could be misunderstanding, but it sounds like what you're suggesting is coming from another angle.

Ultimately what I'd like to do is add arbitrary data from the ship to the frontend `window` object. It feels like this would only be a relatively small tweak, unless the ship's name itself resides in some outer layer and accessing an arbitrary file inside the ship requires a totally different approach. How would I do this?

**Comment by matildepark** [comment]
Oh. Well, yeah, that’s outside the boilerplate’s purview — we pass window.ship much like we pass window.api, I believe those are both provided by eyre, the HTTP server? What I was showing was how you could pass arbitrary data from back-end to front-end.

If you want things to be injected into the window object — not as a JSON object replying to a subscription upon loading the page — you would have to finagle something with Udon to programmatically generate and inject state as part of the page. Publish does something similar. For most cases I would recommend the subscription method.

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
Ok, that is good to know. It sounds like a subscription is what I'll want to do then (using the `window` object to pass arbitrary data isn't the most elegant solution anyway).

So I guess my question now is how do I "open a subscription", given that I have made the changes you suggested?

**Comment by matildepark** [comment]
Full apps do it here, if you uncomment:

https://github.com/urbit/create-landscape-app/blob/master/full/src/js/subscription.js#L16

Tile apps don’t manually open subscriptions, they automatically pass information from the /appname wire through the Launch application to the tile, so you’d write back-end code for answering that wire with specific JSON.

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
I'm having trouble accessing `our`:

```
-find.our
ford: %slim failed: 
ford: %ride failed to compute type:
ford: %plan failed: 
ford: %core on /~donbec-rivmes/home/0/app/myappname/hoon failed:
```

**Comment by matildepark** [comment]
Oh, I guess it’s not in the environment … maybe pass in =our in the gate at the start of the arm?

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
From what I can tell, looks like it is in `our.bol`...not sure what `bol` is. Anyway, that got rid of those `ford` errors, but now in my browser console I encounter an error saying:

```
index.js:61999 /~<my-ship-name>/home/0/lib/default-agent/hoon:<[25 3].[25 5]>
"unexpected subscription to %<myappname> on path /primary"
```

This is after uncommenting the relevant code in `subscription.js`.

**Comment by matildepark** [comment]
Yes, your app isn’t programmed on-watch to handle a subscription on the “/primary” wire. Change /primary in subscription.js to what the path you’re checking for in on-watch.

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
I'm not sure what that path should be, or is.

**Comment by matildepark** [comment]
It looks like just “/“.

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
It's still giving me the same error.

```
/~<my-ship-name>/home/0/lib/default-agent/hoon:<[25 3].[25 5]>
"unexpected subscription to %<myappname> on path /"
```

**Comment by matildepark** [comment]
It falls back to default-agent when the path doesn’t match … you can always just manually set it to something on both ends — on-watch’s equality check (“?. (/ path)” is comparing the watched path with the desired one, “/“) and in subscription.js.

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
Ok, now at least I'm getting something from the subscription, albeit an error. I'm trying a `GET` request in the relevant functions in `subscription.js` and am getting a `404`.

![image](https://user-images.githubusercontent.com/19479857/78727388-88308c80-7902-11ea-850b-151a75de57b4.png)

It makes sense that there isn't anything there to `GET`. How do I take the next step and make it grab a certain file?

**Comment by matildepark** [comment]
I believe it’s a PUT.

—
~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
Yeah, I tried that beforehand and got a similar response. I tried `GET` because I wasn't really trying to `PUT` anything anyway.

Here's the response from `PUT`:

![image](https://user-images.githubusercontent.com/19479857/78728961-c92aa000-7906-11ea-9d42-ed687be8b341.png)

**Comment by cxk280** [comment]
@matildepark Do you have time to pull up over a Zoom call about this? Tried emailing you a few days ago at the email listed on your Github profile but never received a response. I'd be super grateful.

**Comment by matildepark** [comment]
And I responded immediately! Did your email put it in spam?

~haddef-sigwen
https://urbit.org

**Comment by cxk280** [comment]
Whoops, it did indeed!

![image](https://user-images.githubusercontent.com/19479857/79024526-329def00-7b51-11ea-934e-af5e417f90de.png)

Sorry about that! Let's follow up via email.

**Comment by cxk280** [comment]
Been playing with this for a while, referring to `weather.hoon` as you suggest, but still can't get much of anywhere. My main breakthrough is that I've got beyond the `404` error I last mentioned above. Now I'm just getting a console log of `null`.  I've tried a few different things with the following line: 

```[[%give %fact ~ %json !>(*json)]~ this]```

Such as replacing `*json` with a number of different hardcoded values, but nothing works. I was able to also get a `null` console log with the following:

```[[%give %fact ~ %tape "data"]~ this]```

Everything else I've tried throws error. There doesn't seem to be a lot of documentation on what this `%give %fact` syntax means. Can you walk me through it?

**Comment by matildepark** [comment]
This template no longer provides anything hoon-side at all. Your ship is injected as part of the software distribution suite under `window.desk` and is surfaced in the interface template.
