### ISSUE TITLE
Provide back-end to front-end communication example

### ISSUE THREAD

**Issue by matildepark** [urbit/create-landscape-app#24]
Right now our full example passes `*json`, we should show an example of responding to a subscription with more than `null`.

**Comment by Datagrdn** [comment]
First of all, thanks for this! I'd love to bump this thread as understanding this template is really helpful for a newbie like me.

I can't quite grok the full function of the generated .hoon file. Is that what creates the tile and launches the React app when the user opens the tile?

Any resources around the JS<->Hoon beyond the integrating-api docs on would be super helpful.

Thanks!

**Comment by matildepark** [comment]
The generated hoon file, on your ship, is a generated Gall agent. Agents have the same set of arms that run in specific scenarios:

- an `on-init` arm, that is run once it's started. We dictate a variable, `launcha`, with a constructed poke to `:launch`; and a variable, `filea`, with a constructed poke to `:file-server`. For launch, we are giving it the URL of a tile image, and a URL for where the tile should redirect. This will affect what you see on your home screen accordingly. For file server, we're telling it to serve the files in /app/appname folder over HTTP at the endpoint /~appname, that it is *not* public and that it is *not* part of the Landscape single page application.

Note that on-init is only run the first time the agent is started. That's it. Any changes and commits won't affect that code if you've started the agent.

- an `on-watch` arm, for behaviour when something subscribes to us. In this case, if we subscribe at the `/` wire, we send a bunted JSON (an empty JSON type) as a `%fact`.

The other arms are basically boilerplate. You may want to review [this Gall guide](https://github.com/timlucmiptev/gall-guide/blob/master/overview.md) for a recent walkthrough of this stuff.

**Comment by matildepark** [comment]
Technically still at large, but feels out of scope. Might want to revisit after https://github.com/urbit/urbit/pull/5877 and https://github.com/urbit/urbit/pull/5878 when the interface simplifies.
