### ISSUE TITLE
Example of using Store to update React props?

### ISSUE THREAD

**Issue by ronreg-ribdev** [urbit/create-landscape-app#38]
I'm having trouble figuring out from the code in this repo how the `Store` data structure is intended to be used. It looks like the `Store` predefines some reducers which make assumptions about what keys are on the JSON handed down from hoon, but doesn't actually update its own state when `handleEvent` is called. `setStateHandler` is provided but never called as far as I can tell. Either way, there doesn't seem to be an obvious way the React element hierarchy is meant to receive new props based on successfully-handled messages.

**Comment by matildepark** [comment]
The store and reducers are the oldest / least considered part of create-landscape-app and I can probably put some work into that soon ... essentially, they date back to June 2019 Chat. 

How it's meant to be used is that you handle events from the ship to the front end purely through store — handleEvent throws the objects into all reducers, which sets the state in a single place, and root.js just uses store as its state.
