### ISSUE TITLE
/~app path doesn't load index.html; index.js doesn't render fully

### ISSUE THREAD

**Issue by basilesportif** [urbit/create-landscape-app#42]
When I create a new app with CLA and start it, it shows up on the Home screen, but clicking to `/~myapp` gives a 404.

If I manually enter `/~myapp/index.html`, I do get the app page, but only the header (see attached screenshot).
<img width="799" alt="Screen Shot 2020-06-23 at 7 27 38 PM" src="https://user-images.githubusercontent.com/65034141/85429638-b0d23500-b587-11ea-9050-657b0256221e.png">

**Comment by matildepark** [comment]
This is because `/index.html` is not in the router:

![image](https://user-images.githubusercontent.com/20846414/85481483-e11dd180-b58f-11ea-8cc4-982a707d5054.png)

This is an upstream issue for urbit/urbit, and I will file.
