### ISSUE TITLE
404s galore

### ISSUE THREAD

**Issue by dylanirlbeck** [urbit/create-landscape-app#48]
Hi all. I've worked through the tutorial several times now but I continue to get 404s when navigating to `https://localhost:9000/~my-app`. I see the necessary files in my fakezod, the Gall app is running, and the tile appears in Landscape (albeit with the broken image icon).

 Is there any recourse? Some advice would be much appreciated. (Note that I already saw the FAQ question about the app not showing up but the proposed solution did not work.)

Thanks!

**Comment by matildepark** [comment]
Does localhost:9000 itself work?

**Comment by dylanirlbeck** [comment]
Okay so I'm not exactly sure what happened, but after launching a brand new fakezod, and a lot of tinkering/restarting, I now see the correct screen at localhost:9000... I'll follow up if I figure out more details around why this was happening. 

Sorry for the inconvenience!

**Comment by dylanirlbeck** [comment]
@matildepark Follow-up: a friend of mine was encountering the same issue and the solution was to clear the browser history/cookies -- upon reflection, this is one thing I tried before I got the page to load properly. Not sure if this provides any insight, but it might help those who experience this issue in the future!
