### ISSUE TITLE
Example of using this tutorial for a tile

### ISSUE THREAD

**Issue by dylanirlbeck** [urbit/create-landscape-app#50]
Hi all. I have a feature/documentation request. In short, I'm interested in creating a Gall app which solely uses the tile to take in user input and display some information. 

Can someone tell me how I'd need to modify the provided code (either JS or Hoon) to render some React within the tile? At the moment it seems to be drawing from `tile.png` but I'd like it to pull from a `tile.js` file, for instance. Thanks so much!

**Comment by matildepark** [comment]
You can no longer create custom tiles as of the June 2020 single-page application update. `:file-server` and `:launch` alike both expect any third party tiles to be an image and a link to the application.

**Comment by dylanirlbeck** [comment]
Got it, thanks so much.
