### ISSUE TITLE
Hyphenated app name issues

### ISSUE THREAD

**Issue by matildepark** [urbit/create-landscape-app#6]
Probably needs to be escaped somewhere in the rename process — kebab-case _should_ work.

**Comment by matildepark** [comment]
This is incorrect, past me — kebab-case *doesn't* work in JavaScript names for obvious reasons. Because our launch app looks for a tile of the same name, mounting it into the window object, it limits our app creation names to, basically, no kebabs.

I've pushed some commits to dehyphenate names to prevent this error. I'm curious if @loganallenc has tips on whether I've gotten my understanding of launch behaviour / inability to use kebab case wrong, though.

**Comment by jfranklin9000** [comment]
Can you convert `my-cool-app` to `myCoolApp` for the JS/JSX stuff?

Like React inline styles: `{{ backgroundColor: 'red' }}` becomes `background-color:red`

Or HTML `data-` attributes: `<div id="foo" data-my-num="42"></div>` becomes `document.querySelector('#foo').dataset.myNum` (https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset#Name_conversion)

**Comment by matildepark** [comment]
No longer at large.
