### ISSUE TITLE
Cannot build on Linux

### ISSUE THREAD

**Issue by techieAgnostic** [urbit/create-landscape-app#7]
`npm install` complains about dependencies being Darwin only.

Steps:
`git clone https://github.com/urbit/create-landscape-app/`
`cd create-landscape-app`
`npm install`

Output (that I got):
```
npm ERR! Linux 4.18.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shaun/mess/repos/create-landscape-app/npm-debug.log
```

**Comment by matildepark** [comment]
Related discussions around `fsevents` recommend running the install with `npm i -f`. 

Talked to @techieAgnostic outside this issue and it seems to rectify. I will document that this is required.
