### ISSUE TITLE
`npm run dev` results in http proxy error

### ISSUE THREAD

**Issue by litlep-nibbyt** [urbit/create-landscape-app#70]
I followed the instructions in the README. After downloading the project using `npx @urbit/create-landscape-app`

1. Booted up `~zod`
2. Ran `npm install` inside the `ui` directory
3. Updated the contents of `.env.local` to contain `VITE_SHIP_URL={~zod}`
4. Ran `|cors-approve ~~http~3a.~2f.~2f.localhost~3a.3000` on `~zod`
5. Ran `npm run dev` inside `ui` folder
6. Went to`http://localhost:3000/apps/create-landscape-app/` in browser

Result:

```
 vite v2.9.14 dev server running at:

  > Local: http://localhost:3000/apps/create-landscape-app/
  > Network: use `--host` to expose

  ready in 246ms.

11:13:56 PM [vite] http proxy error:
Error: socket hang up
    at connResetException (node:internal/errors:692:14)
    at Socket.socketOnEnd (node:_http_client:478:23)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Oddly enough the app loads when I `ctrl-c`.

**Comment by matildepark** [comment]
Your ship URL isn’t “zod” — it’s localhost and some port usually.

**Comment by litlep-nibbyt** [comment]
good catch, I updated it to `VITE_SHIP_URL={http://localhost:8080}` but it's still giving me the same error.

**Comment by matildepark** [comment]
No brackets. Try `VITE_SHIP_URL=http://localhost:8080`.

Also doesn't `npx @urbit/create-landscape-app` ask you to name the app? Did you name it `create-landscape-app`?

**Comment by litlep-nibbyt** [comment]
I had Docker Desktop running, so I turned it off. Now I'm getting

```
12:36:40 AM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) (x4)
```

**Comment by matildepark** [comment]
Well, that's because it's trying to connect to port 80.

**Comment by matildepark** [comment]
Basically even if you have nothing committed on the ship a FE interface should proxy neatly. If the socket dies, you might want to go to localhost:3000 directly and sign in and then try going to the endpoint.

**Comment by litlep-nibbyt** [comment]
> I had Docker Desktop running, so I turned it off. Now I'm getting
> 
> ```
> 12:36:40 AM [vite] http proxy error:
> Error: connect ECONNREFUSED 127.0.0.1:80
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) (x4)
> ```

Sorry, I didn't see your prior messages when I sent this. It's working now! I think it was the brackets that were causing the problem. Thanks for your help
