### ISSUE TITLE
Use urbit/vite-plugin-urbit instead

### ISSUE THREAD

**Issue by ajlamarc** [urbit/create-landscape-app#81]
I originally created `@holium/vite-plugin-urbit` for Vite 4 support, but now urbit/vite-plugin-urbit supports Vite 4.

https://github.com/urbit/vite-plugin-urbit

**Comment by toddux-dopnel** [comment]
Fixed in https://github.com/urbit/create-landscape-app/pull/82. This one can be closed if the PR is accepted and merged.

**Comment by toddux-dopnel** [comment]
@pkova thanks for merging #82 ... you can close this issue since it was fixed with that PR
